export default {
  'tagname-lowercase': true,
  'attr-lowercase': true,
  'attr-value-double-quotes': true,
  'attr-no-duplication': true,
  'id-unique': true,
  'tag-pair': true,
  'tag-self-close': true,
  'spec-char-escape': true,
  'attr-value-not-empty': true,
  'attr-whitespace': true,
  'attr-no-unnecessary-whitespace': true,
  'attr-value-no-duplication': true,
  'tag-no-obsolete': true,
  'tagname-specialchars': true,
  'script-disabled': true,
  'style-disabled': true,
  'alt-require': true,
  'id-class-value': 'dash',
}
